# Form implementation generated from reading ui file 'uics/ProcessView.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 680)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.processTreeWidget = QtWidgets.QTreeWidget(parent=Dialog)
        self.processTreeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.processTreeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.processTreeWidget.setRootIsDecorated(True)
        self.processTreeWidget.setObjectName("processTreeWidget")
        self.processTreeWidget.header().setDefaultSectionSize(64)
        self.processTreeWidget.header().setMinimumSectionSize(64)
        self.processTreeWidget.header().setSortIndicatorShown(True)
        self.processTreeWidget.header().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.processTreeWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLineEdit.sizePolicy().hasHeightForWidth())
        self.searchLineEdit.setSizePolicy(sizePolicy)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.horizontalLayout.addWidget(self.searchLineEdit)
        self.clearButton = QtWidgets.QPushButton(parent=Dialog)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        self.attachButton = QtWidgets.QPushButton(parent=Dialog)
        self.attachButton.setObjectName("attachButton")
        self.horizontalLayout.addWidget(self.attachButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.clearButton.clicked.connect(self.searchLineEdit.clear) # type: ignore
        self.attachButton.clicked.connect(Dialog.return_selected_pid) # type: ignore
        self.clearButton.clicked.connect(self.processTreeWidget.clearSelection) # type: ignore
        self.searchLineEdit.textChanged['QString'].connect(Dialog.search_filter) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ProcessViewer"))
        self.processTreeWidget.setSortingEnabled(True)
        self.processTreeWidget.headerItem().setText(0, _translate("Dialog", "Process"))
        self.processTreeWidget.headerItem().setText(1, _translate("Dialog", "PID"))
        self.searchLineEdit.setPlaceholderText(_translate("Dialog", "Search"))
        self.clearButton.setText(_translate("Dialog", "Clear"))
        self.attachButton.setText(_translate("Dialog", "Attach"))
